### ISSUE TITLE
Building from AUR fails

### ISSUE THREAD

**Issue by LumbaBalumba** [poac-dev/poac#935] opened 2024-06-03 00:10 UTC
I get this error while trying to install poac from AUR:

/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Semver.cc -o build-out/Semver.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/TermColor.cc -o build-out/TermColor.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Parallel.cc -o build-out/Parallel.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/BuildConfig.cc -o build-out/BuildConfig.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Time.cc -o build-out/Git2/Time.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Describe.cc -o build-out/Git2/Describe.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Object.cc -o build-out/Git2/Object.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Version.cc -o build-out/Git2/Version.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Repository.cc -o build-out/Git2/Repository.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Config.cc -o build-out/Git2/Config.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Oid.cc -o build-out/Git2/Oid.o
/usr/bin/clang++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -O3 -DNDEBUG -flto -MMD -DPOAC_PKG_VERSION='"0.9.3"' -DPOAC_COMMIT_HASH='"11014aaf6b82804eb9928328fd411d6c677ba7c8"' -DPOAC_COMMIT_SHORT_HASH='"11014aa"' -DPOAC_COMMIT_DATE='"2024-02-03"' -isystem build-out/DEPS/toml11     -c src/Git2/Exception.cc -o build-out/Git2/Exception.o
src/Git2/Exception.cc:28:5: error: use of undeclared identifier 'git_error_clear'
   28 |     git_error_clear();
      |     ^
1 error generated.
make: *** [Makefile:57: build-out/Git2/Exception.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: poac-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
poac - exit status 4

**Comment by ken-matsui** [comment] 2024-06-03 00:13
This is clearly a duplicate of https://github.com/poac-dev/poac/issues/930, and I am not maintaining the Poac AUR package.

**Closed by ken-matsui** 2024-06-03 00:13 UTC
